version: "2.1"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.template
    ports:
      - "80:80"
    networks:
      - internal
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.template
    ports:
      - "3001:3001"
    networks:
      - internal
    restart: unless-stopped

networks:
  internal: {}
