FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:bullseye

# Set our working directory
WORKDIR /usr/src/app

# Install app dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# This will copy all files in our root to the working  directory in the container
COPY . ./

# Enable udevd so that plugged dynamic hardware devices show up in our container.
#ENV UDEV=1

# main.py will run when container starts up on the device
CMD ["python","-u","src/main.py"]
